forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache', '3.1.0'
mod 'puppet-php', '5.3.0'
mod 'biemond-oradb', '3.0.15'
mod 'puppetlabs-java', '2.4.0'
mod 'petems-swap_file', '4.0.0'
mod 'jamesnetherton-google_chrome', '0.4.0'
mod 'puppet-nodejs', '5.0.0'
mod 'camptocamp-openssl', '1.10.0'
mod 'puppetlabs-mysql', '5.4.0'
mod 'puppetlabs-firewall', '1.12.0'
mod 'ghoneycutt-ssh', '3.57.0'
mod 'puppetlabs-git', '0.5.0'
mod 'puppetlabs-vcsrepo', '2.3.0'
